/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hydon
 */
import java.awt.Image;
import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;

public class anaForm extends javax.swing.JFrame {

    static DefaultTableModel modelim = new DefaultTableModel();
    static Object[] sutun = {"fatura kayit no", "Faturan ture", "fatura tarihi", "Fatura Odeme Tarihi", "Fatura Miktari", "Odemeye AitDekont"};//sutunlarimizi ismini yazmak icin bir object olusturuyoruz

    static Object[] satirlar = new Object[9];

    static DefaultTableModel modelim2 = new DefaultTableModel();
    static Object[] sutun2 = {"garanti belge no", "Urunun Turu", "Urunun Markasi", "Urunun Modeli", "Urunun Adi", "Urunun Seri Numarasi", "Urunun Garanti Bitis Tarihi", "Urunun Faturasi"};//sutunlarimizi ismini yazmak icin bir object olusturuyoruz

    static Object[] satirlar2 = new Object[8];

    /**
     *
     *
     * Creates new form frm1
     */
    public anaForm() {

        initComponents();
        formuniconunuayarla();
        tablolarigetir();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        faturaislemleri = new javax.swing.JButton();
        label1 = new java.awt.Label();
        garantibelgesiislemleri = new javax.swing.JButton();
        label2 = new java.awt.Label();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Evim");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        setForeground(java.awt.Color.black);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(116, 212, 192));
        jPanel3.setRequestFocusEnabled(false);

        faturaislemleri.setBackground(new java.awt.Color(255, 216, 166));
        faturaislemleri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        faturaislemleri.setText("Fatura İslemleri");
        faturaislemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturaislemleriActionPerformed(evt);
            }
        });

        label1.setBackground(new java.awt.Color(116, 212, 192));
        label1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label1.setText("Faturalarınız:");

        garantibelgesiislemleri.setBackground(new java.awt.Color(255, 216, 166));
        garantibelgesiislemleri.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        garantibelgesiislemleri.setText("Garanti Belgesi İslemleri");
        garantibelgesiislemleri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                garantibelgesiislemleriActionPerformed(evt);
            }
        });

        label2.setBackground(new java.awt.Color(116, 212, 192));
        label2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        label2.setText("Garanti Belgeleriniz:");

        jTable3.setModel(modelim);
        jScrollPane1.setViewportView(jTable3);

        jTable1.setModel(modelim2);
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(garantibelgesiislemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(faturaislemleri, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1135, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(faturaislemleri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(garantibelgesiislemleri)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void garantibelgesiislemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_garantibelgesiislemleriActionPerformed
        // TODO add your handling code here:
        GarantiİşlemleriFormu islem = new GarantiİşlemleriFormu();
        islem.setVisible(true);
    }//GEN-LAST:event_garantibelgesiislemleriActionPerformed

    private void faturaislemleriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturaislemleriActionPerformed
        // TODO add your handling code here:
        FaturaİslemleriFormu islem = new FaturaİslemleriFormu();
        islem.setVisible(true);
    }//GEN-LAST:event_faturaislemleriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton faturaislemleri;
    private javax.swing.JButton garantibelgesiislemleri;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private java.awt.Label label1;
    private java.awt.Label label2;
    // End of variables declaration//GEN-END:variables

    public void tablolarigetir() {
        veritabanibaglanti baglanti = new veritabanibaglanti();
        ResultSet res = baglanti.soneklenefaturalar();
        modelim.setColumnIdentifiers(sutun);//yukarda tanimladigimiz sutunlari columaekledik icine attik
        try {
            while (res.next()) {
                satirlar[0] = res.getString("fatura_kayitno");
                satirlar[1] = res.getString("fatura_turu");
                satirlar[2] = res.getString("fatura_tarihi");
                satirlar[3] = res.getString("fatura_odemetarihi");
                satirlar[4] = res.getString("fatura_miktari");
                satirlar[5] = res.getString("fatura_dekont");

                modelim.addRow(satirlar);//yukarida tanimladigimiz satirlari rowsa ekledik 		
            }

            //garanti s�resi azalan �r�nler
            ResultSet res1 = baglanti.garantisisuresiazalanurunler();
            modelim2.setColumnIdentifiers(sutun2);
            while (res1.next()) {
                satirlar2[0] = res1.getString("garantibelge_kayitno");
                satirlar2[1] = res1.getString("garantibelge_urununturu");
                satirlar2[2] = res1.getString("garantibelge_urununmarkasi");
                satirlar2[3] = res1.getString("garantibelge_urununmodeli");
                satirlar2[4] = res1.getString("garantibelge_urununadi");
                satirlar2[5] = res1.getString("garantibelge_urununserino");
                satirlar2[6] = res1.getString("garantibelge_urunungarantibitissuresi");
                satirlar2[7] = res1.getString("garantibelge_urununfaturasi");

                modelim2.addRow(satirlar2);//yukarida tanimladigimiz satirlari rowsa ekledik 

                //!!! burada formun desing kısmından model kısmına gelip oraya modelimizzin konudu yazdık tablo böyle çalışıyor
            }

        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }

    void formuniconunuayarla() {
        Image Evim = new ImageIcon(anaForm.class.getResource("Evim.jpg")).getImage();//resmi çektik burada classin ismi yazılacak burada ilk ilgili class için 
        setIconImage(Evim);
    }
}
