
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hydon
 */
public class FaturaEklemeFormu extends javax.swing.JFrame {

    /**
     * Creates new form FaturaEklemeFormu
     */
    public FaturaEklemeFormu() {

        initComponents();
        soykayitnogetir();
        formuniconunuayarla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cmbx_faturaturu = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        dc_faturaodemetarihi = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();
        dc_faturatarihi = new com.toedter.calendar.JDateChooser();
        jButton1 = new javax.swing.JButton();
        txt_faturano = new javax.swing.JTextField();
        txt_faturamiktari = new javax.swing.JTextField();
        txt_faturadekont = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fatura Ekleme Formu");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Fatura Kayit No:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fatura Turu:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 85, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fatura Tarihi:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fatura Odeme Tarihi:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        cmbx_faturaturu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik", "Telefon", "Su", "Dogal Gaz", "Digerleri" }));
        jPanel1.add(cmbx_faturaturu, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 32, 132, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fatura Miktari:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        dc_faturaodemetarihi.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.add(dc_faturaodemetarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 132, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fatura Ait Dekont:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        dc_faturatarihi.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.add(dc_faturatarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 60, 132, -1));

        jButton1.setBackground(new java.awt.Color(255, 216, 166));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Fatura Ekle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 132, 30));

        txt_faturano.setText("1");
        jPanel1.add(txt_faturano, new org.netbeans.lib.awtextra.AbsoluteConstraints(168, 6, 132, -1));

        txt_faturamiktari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_faturamiktariKeyTyped(evt);
            }
        });
        jPanel1.add(txt_faturamiktari, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 120, 132, -1));

        txt_faturadekont.setToolTipText("");
        txt_faturadekont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_faturadekontMouseClicked(evt);
            }
        });
        jPanel1.add(txt_faturadekont, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        int faturano = Integer.parseInt(txt_faturano.getText());
        String faturaturu = cmbx_faturaturu.getSelectedItem().toString();

        int faturamiktari = Integer.parseInt(txt_faturamiktari.getText());

        String faturadekont = txt_faturadekont.getText();
        faturadekont = faturadekont.replace("\\", "/");//java tersslahi kacis ifadesi olarak kullaniyor veritabanina eklemiyor o yuzden degisiriyoruz

        veritabanibaglanti baglanti = new veritabanibaglanti();

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");//tarih formatını veritabanına eklemek için gerekli kodlar
        String faturatarihi = format.format(dc_faturatarihi.getDate());
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String faturaodemetarihi = format1.format(dc_faturaodemetarihi.getDate());
        String sql_sorgu = "INSERT INTO fatura_tbl (fatura_kayitno,fatura_turu, fatura_tarihi, fatura_odemetarihi,fatura_miktari, fatura_dekont)  VALUES (" + faturano + ",'" + faturaturu + "','" + faturatarihi + "','" + faturaodemetarihi + "'," + faturamiktari + ",'" + faturadekont + "')";
        baglanti.sqlislemler(sql_sorgu);

        soykayitnogetir();//en son kayitnosunu bulup bir artiriyor elle giriste olusacak hataları engellemek icin

        JOptionPane.showMessageDialog(null, "Kaydınız Basarıyla Tamamlanmıştır");
        temizle();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txt_faturamiktariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_faturamiktariKeyTyped
        // TODO add your handling code here:
        //sadece sayı girmeye izin verir
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_faturamiktariKeyTyped

    private void txt_faturadekontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_faturadekontMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "png", "gif");//Fitreliyoruz
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));//Gecerli projenin dosya yolu
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try {
                txt_faturadekont.setText(selectedFile.getCanonicalPath());
            } catch (IOException ex) {
                Logger.getLogger(FaturaEklemeFormu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txt_faturadekontMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        
        
        
        
         */

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaEklemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaEklemeFormu().setVisible(true);

            }
        });
    }

    public void temizle() {
        txt_faturadekont.setText("");
        txt_faturamiktari.setText("");
        cmbx_faturaturu.setSelectedIndex(0);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbx_faturaturu;
    private com.toedter.calendar.JDateChooser dc_faturaodemetarihi;
    private com.toedter.calendar.JDateChooser dc_faturatarihi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_faturadekont;
    private javax.swing.JTextField txt_faturamiktari;
    private javax.swing.JTextField txt_faturano;
    // End of variables declaration//GEN-END:variables
void soykayitnogetir() {
        try {
            veritabanibaglanti baglanti = new veritabanibaglanti();
            ResultSet res = baglanti.faturasonkayit();
            while (res.next()) {
                txt_faturano.setText(String.valueOf(res.getInt("fatura_kayitno") + 1));//en son kayitnosunu bulup bir artiriyor

            }

        } catch (Exception e) {
            // TODO: handle exception
        }
        txt_faturano.setEnabled(false);

    }

    void formuniconunuayarla() {
        Image Evim = new ImageIcon(FaturaEklemeFormu.class.getResource("Evim.jpg")).getImage();//resmi çektik burada classin ismi yazılacak burada ilk ilgili class için 
        setIconImage(Evim);
    }
}
