
import java.awt.Desktop;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hydon
 */
public class FaturaDuzenlemeFormu extends javax.swing.JFrame {

    static DefaultTableModel modelim = new DefaultTableModel();
    static Object[] sutun = {"fatura kayit no", "Faturan turu", "fatura tarihi", "Fatura Odeme Tarihi", "Fatura Miktari", "Odemeye AitDekont"};//sutunlarimiza ismini yazmak icin bir object olusturuyoruz

    static Object[] satirlar = new Object[9];

    /**
     * Creates new form FaturaDuzenlemeFormu
     */
    public FaturaDuzenlemeFormu() {

        initComponents();
        tabloguncelle();
        formuuniconunuAyarla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        buton_temizle = new javax.swing.JButton();
        button_goster = new javax.swing.JButton();
        txt_faturano = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_faturamiktari = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_faturadekont = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbx_faturaturu = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        dc_faturatarihi = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        dc_faturaodemetarihi = new com.toedter.calendar.JDateChooser();
        buton_listele = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        buton_guncelle = new javax.swing.JButton();
        buton_sil = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fatura Duzenleme Formu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buton_temizle.setBackground(new java.awt.Color(255, 216, 166));
        buton_temizle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buton_temizle.setText("Temizle");
        buton_temizle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_temizleActionPerformed(evt);
            }
        });
        jPanel1.add(buton_temizle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 135, -1));

        button_goster.setBackground(new java.awt.Color(255, 216, 166));
        button_goster.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        button_goster.setText("Faturayı Goster");
        button_goster.setEnabled(false);
        button_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_gosterActionPerformed(evt);
            }
        });
        jPanel1.add(button_goster, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 160, -1, -1));
        jPanel1.add(txt_faturano, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 156, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Fatura Kayit No:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        txt_faturamiktari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_faturamiktariKeyTyped(evt);
            }
        });
        jPanel1.add(txt_faturamiktari, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 130, 156, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Fatura Turu:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        txt_faturadekont.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_faturadekontMouseClicked(evt);
            }
        });
        txt_faturadekont.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faturadekontActionPerformed(evt);
            }
        });
        jPanel1.add(txt_faturadekont, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 156, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Fatura Tarihi:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Fatura Odeme Tarihi:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cmbx_faturaturu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Elektrik", "Telefon", "Su", "Dogal Gaz", "Digerleri" }));
        jPanel1.add(cmbx_faturaturu, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 156, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Fatura Miktari:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 10));

        dc_faturatarihi.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.add(dc_faturatarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 156, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fatura Ait Dekont:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, -1));

        dc_faturaodemetarihi.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.add(dc_faturaodemetarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 156, -1));

        buton_listele.setBackground(new java.awt.Color(255, 216, 166));
        buton_listele.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buton_listele.setText("Faturayi Listele");
        buton_listele.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_listeleActionPerformed(evt);
            }
        });
        jPanel1.add(buton_listele, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jTable3.setModel(modelim);
        jScrollPane1.setViewportView(jTable3);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 708, 118));

        buton_guncelle.setBackground(new java.awt.Color(255, 216, 166));
        buton_guncelle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buton_guncelle.setText("Faturayi Guncelle");
        buton_guncelle.setEnabled(false);
        buton_guncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_guncelleActionPerformed(evt);
            }
        });
        jPanel1.add(buton_guncelle, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, -1, -1));

        buton_sil.setBackground(new java.awt.Color(255, 216, 166));
        buton_sil.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        buton_sil.setText("Faturayi Sil");
        buton_sil.setEnabled(false);
        buton_sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_silActionPerformed(evt);
            }
        });
        jPanel1.add(buton_sil, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 125, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Mevcut Faturalar(Azalan Sıralama)");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_gosterActionPerformed
        // TODO add your handling code here:

        File file = new File("");

        //first check if Desktop is supported by Platform or not
        if (!Desktop.isDesktopSupported()) {
            System.out.println("Desktop is not supported");
            return;
        }

        Desktop desktop = Desktop.getDesktop();
        if (file.exists()) {
            try {
                desktop.open(file);
            } catch (IOException ex) {
                Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //let's try to open PDF file
        file = new File(txt_faturadekont.getText());
        if (file.exists()) {
            try {
                desktop.open(file);
            } catch (IOException ex) {
                Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_button_gosterActionPerformed

    private void buton_listeleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_listeleActionPerformed
        // TODO add your handling code here:
        int faturano = Integer.parseInt(txt_faturano.getText());
        veritabanibaglanti islem = new veritabanibaglanti();
        String sqlsorgu = "select*from fatura_tbl where fatura_kayitno=" + faturano;
        ResultSet sonuc = null;
        sonuc = islem.verilisteleme(sqlsorgu);

        try {
            while (sonuc.next()) {
                txt_faturano.setText(sonuc.getString("fatura_kayitno"));

                txt_faturamiktari.setText(sonuc.getString("fatura_miktari"));
                txt_faturadekont.setText(sonuc.getString("fatura_dekont"));
                cmbx_faturaturu.setSelectedItem(sonuc.getString("fatura_turu"));

                String faturatarihi = sonuc.getString("fatura_tarihi");//tarihi jchoosera çekmek için ilk bir stringe çekiyoruz sonra alttarafta pars edip ekliyoruz
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(faturatarihi);///yukarda devamı

                String odemetarihi = sonuc.getString("fatura_odemetarihi");//tarihi jchoosera çekmek için ilk bir stringe çekiyoruz sonra alttarafta pars edip ekliyoruz
                Date date1 = new SimpleDateFormat("yyyy-MM-dd").parse(odemetarihi);///yukarda devamı

                dc_faturatarihi.setDate(date);

                dc_faturaodemetarihi.setDate(date1);
                JOptionPane.showMessageDialog(null, "Kaydınız Basarıyla Listelenmistir!");

            }
            txt_faturano.setEnabled(false);
            buton_guncelle.setEnabled(true);
            buton_sil.setEnabled(true);
            button_goster.setEnabled(true);

        } catch (Exception e) {

        }


    }//GEN-LAST:event_buton_listeleActionPerformed

    private void buton_silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_silActionPerformed
        // TODO add your handling code here:

        modelim.setRowCount(0);
        int no = Integer.parseInt(txt_faturano.getText());
        String sqlsorgu = "delete from fatura_tbl where fatura_kayitno=" + no;
        veritabanibaglanti baglanti = new veritabanibaglanti();
        baglanti.sqlislemler(sqlsorgu);
        JOptionPane.showMessageDialog(null, "Kaydınızı Basarıyla Sildiniz !");
        tabloguncelle();//tabloyu sildikten sonra güncellemek için 

        temizle();
    }//GEN-LAST:event_buton_silActionPerformed

    private void buton_guncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_guncelleActionPerformed
        // TODO add your handling code here:

        veritabanibaglanti islem = new veritabanibaglanti();
        int faturano = Integer.parseInt(txt_faturano.getText());
        String faturaturu = cmbx_faturaturu.getSelectedItem().toString();
        int faturamiktari = Integer.parseInt(txt_faturamiktari.getText());
        String faturadekont = txt_faturadekont.getText();
        faturadekont = faturadekont.replace("\\", "/");
        veritabanibaglanti baglanti = new veritabanibaglanti();
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String faturatarihi = format.format(dc_faturatarihi.getDate());
        SimpleDateFormat format1 = new SimpleDateFormat("yyyy-MM-dd");
        String faturaodemetarihi = format1.format(dc_faturaodemetarihi.getDate());

        String sqlsorgu = "update fatura_tbl set fatura_kayitno=" + faturano + "," + "fatura_miktari=" + faturamiktari + ",fatura_dekont='" + faturadekont + "',fatura_turu='" + faturaturu + "',fatura_tarihi='" + faturatarihi + "',fatura_odemetarihi='" + faturaodemetarihi + "'where fatura_kayitno=" + faturano;
        islem.guncelleme(sqlsorgu);
        JOptionPane.showMessageDialog(null, "Kaydınızı Basarıyla Guncellediniz !");
        tabloguncelle();

        temizle();
    }//GEN-LAST:event_buton_guncelleActionPerformed

    private void buton_temizleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_temizleActionPerformed
        // TODO add your handling code here:
        temizle();
    }//GEN-LAST:event_buton_temizleActionPerformed

    private void txt_faturadekontMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_faturadekontMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "png", "gif");//Fitreliyoruz
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));//Gecerli projenin dosya yolu
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txt_faturadekont.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_txt_faturadekontMouseClicked

    private void txt_faturadekontActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faturadekontActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_faturadekontActionPerformed

    private void txt_faturamiktariKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_faturamiktariKeyTyped
        // TODO add your handling code here:
        //sadece sayı girmeye izin verir
        char vChar = evt.getKeyChar();
        if (!(Character.isDigit(vChar) || (vChar == KeyEvent.VK_BACK_SPACE) || (vChar == KeyEvent.VK_DELETE))) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_faturamiktariKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FaturaDuzenlemeFormu().setVisible(true);
            }
        });
    }

    public void temizle() {
        txt_faturadekont.setText("");
        txt_faturamiktari.setText("");
        txt_faturano.setText("");

        cmbx_faturaturu.setSelectedIndex(0);

        txt_faturano.setEnabled(true);
        buton_sil.setEnabled(false);
        buton_guncelle.setEnabled(false);
        button_goster.setEnabled(false);
    }

    public void tabloguncelle() {
        modelim.setRowCount(0);
        try {
            veritabanibaglanti veribaglanti = new veritabanibaglanti();
            ResultSet res = veribaglanti.soneklenefaturalar();
            modelim.setColumnIdentifiers(sutun);//yukarda tanımladıgimiz sutunlari columaekledik icine attik
            while (res.next()) {
                satirlar[0] = res.getString("fatura_kayitno");
                satirlar[1] = res.getString("fatura_turu");
                satirlar[2] = res.getString("fatura_tarihi");
                satirlar[3] = res.getString("fatura_odemetarihi");
                satirlar[4] = res.getString("fatura_miktari");
                satirlar[5] = res.getString("fatura_dekont");

                modelim.addRow(satirlar);//yukarida taımladığımız satirları rowsa ekledik 		
            }

        } catch (Exception e) {
            // TODO: handle exception
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_guncelle;
    private javax.swing.JButton buton_listele;
    private javax.swing.JButton buton_sil;
    private javax.swing.JButton buton_temizle;
    private javax.swing.JButton button_goster;
    private javax.swing.JComboBox<String> cmbx_faturaturu;
    private com.toedter.calendar.JDateChooser dc_faturaodemetarihi;
    private com.toedter.calendar.JDateChooser dc_faturatarihi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField txt_faturadekont;
    private javax.swing.JTextField txt_faturamiktari;
    private javax.swing.JTextField txt_faturano;
    // End of variables declaration//GEN-END:variables
void formuuniconunuAyarla() {
        Image Evim = new ImageIcon(FaturaDuzenlemeFormu.class.getResource("Evim.jpg")).getImage();//resmi çektik burada classin ismi yazılacak burada ilk ilgili class için 
        setIconImage(Evim);
    }
}
