
import com.sun.corba.se.spi.orb.OperationFactory;
import java.awt.Desktop;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author hydon
 */
public class GarantiBelgesiDuzenlemeFormu extends javax.swing.JFrame {

    private static DefaultTableModel modelim = new DefaultTableModel();
    private static Object[] sutun = {"garanti belge no", "Urunun Turu", "Urunun Markasi", "Urunun Modeli", "Urunun Adi", "Urunun Seri Numarasi", "Urunun Garanti Bitis Tarihi", "Urunun Faturasi"};//sutunlarimizi ismini yazmak icin bir object olusturuyoruz

    static Object[] satirlar = new Object[8];

    /**
     * Creates new form GarantiBelgesiDuzenlemeFormu
     */
    public GarantiBelgesiDuzenlemeFormu() {

        initComponents();
        listeguncelle();
        formuniconunuayarla();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_belgeno = new javax.swing.JTextField();
        cmbx_urunturu = new javax.swing.JComboBox<>();
        txt_marka = new javax.swing.JTextField();
        txt_model = new javax.swing.JTextField();
        txt_urunadi = new javax.swing.JTextField();
        txt_serino = new javax.swing.JTextField();
        dc_garantibitistarihi = new com.toedter.calendar.JDateChooser();
        txt_fatura = new javax.swing.JTextField();
        listele_buton = new javax.swing.JButton();
        sil_buton = new javax.swing.JButton();
        guncelle_buton = new javax.swing.JButton();
        temizle_buton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        buton_goster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Garanti Belgesi Duzenleme Formu");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(116, 212, 192));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Garanti Belge No:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Urunun Turu:");
        jLabel2.setToolTipText("");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Urunun Markasi:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Urunun Modeli:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 110, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Urunun Adi:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Urunun Seri No:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 120, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Garanti Bitis Tarihi");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 120, 10));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Urunun Faturasi");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 120, -1));
        jPanel1.add(txt_belgeno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 140, -1));

        cmbx_urunturu.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Telefon", "Bilgisayar", "Bilgisayar Birimleri", "Televizyon", "Beyaz Esya", "Ev Aletleri", "Mobilya", "Aksesuar", "Diger" }));
        jPanel1.add(cmbx_urunturu, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, -1));
        jPanel1.add(txt_marka, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, -1));
        jPanel1.add(txt_model, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, -1));
        jPanel1.add(txt_urunadi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, -1));
        jPanel1.add(txt_serino, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, -1));
        jPanel1.add(dc_garantibitistarihi, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, -1));

        txt_fatura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_faturaMouseClicked(evt);
            }
        });
        txt_fatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_faturaActionPerformed(evt);
            }
        });
        jPanel1.add(txt_fatura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, -1));

        listele_buton.setBackground(new java.awt.Color(255, 216, 166));
        listele_buton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listele_buton.setText("Garanti Belgesini Listele");
        listele_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listele_butonActionPerformed(evt);
            }
        });
        jPanel1.add(listele_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        sil_buton.setBackground(new java.awt.Color(255, 216, 166));
        sil_buton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sil_buton.setText("Garanti Belgesini Sil");
        sil_buton.setEnabled(false);
        sil_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_butonActionPerformed(evt);
            }
        });
        jPanel1.add(sil_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 180, -1));

        guncelle_buton.setBackground(new java.awt.Color(255, 216, 166));
        guncelle_buton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        guncelle_buton.setText("Garanti Belgesini Guncelle");
        guncelle_buton.setEnabled(false);
        guncelle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guncelle_butonActionPerformed(evt);
            }
        });
        jPanel1.add(guncelle_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 250, 190, -1));

        temizle_buton.setBackground(new java.awt.Color(255, 216, 166));
        temizle_buton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        temizle_buton.setText("Temizle");
        temizle_buton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                temizle_butonActionPerformed(evt);
            }
        });
        jPanel1.add(temizle_buton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 280, 180, -1));

        jTable1.setModel(modelim);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 620, 120));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Mevcut Olan Belgeleriniz(Garanti Süresi Azalan Urunler Basta)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, -1, -1));

        buton_goster.setBackground(new java.awt.Color(255, 216, 166));
        buton_goster.setText("Faturayı Goster");
        buton_goster.setEnabled(false);
        buton_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buton_gosterActionPerformed(evt);
            }
        });
        jPanel1.add(buton_goster, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 900, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listele_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listele_butonActionPerformed
        // TODO add your handling code here:

        int belgeno = Integer.parseInt(txt_belgeno.getText());
        veritabanibaglanti islem = new veritabanibaglanti();
        String sqlsorgu = "select*from garantibelge_tbl where garantibelge_kayitno=" + belgeno;
        ResultSet sonuc = null;
        sonuc = islem.verilisteleme(sqlsorgu);

        try {
            while (sonuc.next()) {

                txt_belgeno.setText(sonuc.getString("garantibelge_kayitno"));

                txt_marka.setText(sonuc.getString("garantibelge_urununmarkasi"));
                txt_model.setText(sonuc.getString("garantibelge_urununmodeli"));
                txt_urunadi.setText(sonuc.getString("garantibelge_urununadi"));
                txt_fatura.setText(sonuc.getString("garantibelge_urununfaturasi"));

                txt_serino.setText(sonuc.getString("garantibelge_urununserino"));
                cmbx_urunturu.setSelectedItem(sonuc.getString("garantibelge_urununturu"));

                String tarih = sonuc.getString("garantibelge_urunungarantibitissuresi");//tarihi jchoosera çekmek için ilk bir stringe çekiyoruz sonra alttarafta pars edip ekliyoruz
                Date date = new SimpleDateFormat("yyyy-MM-dd").parse(tarih);///yukarda devamı

                dc_garantibitistarihi.setDate(date);
                JOptionPane.showMessageDialog(null, "Kaydınız Basarıyla Listelenmistir!");

            }

            txt_belgeno.setEnabled(false);
            sil_buton.setEnabled(true);

            guncelle_buton.setEnabled(true);
            temizle_buton.setEnabled(true);
            buton_goster.setEnabled(true);

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(null, "hatayakalandi", "kayıttablosu", JOptionPane.PLAIN_MESSAGE);
        }

        ////listeleme yapılacak 

    }//GEN-LAST:event_listele_butonActionPerformed

    private void guncelle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guncelle_butonActionPerformed
        // TODO add your handling code here:

        veritabanibaglanti islem = new veritabanibaglanti();
        int belgeno = Integer.parseInt(txt_belgeno.getText());
        String marka = txt_marka.getText();
        String turu = cmbx_urunturu.getSelectedItem().toString();
        String model = txt_model.getText();
        String urunadi = txt_urunadi.getText();
        String fatura = txt_fatura.getText();
        fatura = fatura.replace("\\", "/");//yolu alırken bu satir yazılmazsa java kacıc olarak goruyor slashı siliyor o yüzden gerekli
        String serino = txt_serino.getText();

        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");//tarih formatinda kaydetme icin gerekli 2 satir kod
        String garantibitistarihi = format.format(dc_garantibitistarihi.getDate());

        String sqlsorgu = "update garantibelge_tbl set garantibelge_kayitno=" + belgeno + "," + "garantibelge_urununturu='" + turu + "',garantibelge_urununmarkasi='" + marka + "',garantibelge_urununmodeli='" + model + "',garantibelge_urununadi='" + urunadi + "',garantibelge_urununserino='" + serino + "',garantibelge_urunungarantibitissuresi='" + garantibitistarihi + "',garantibelge_urununfaturasi='" + fatura + "'where garantibelge_kayitno=" + belgeno;
        islem.guncelleme(sqlsorgu);
        JOptionPane.showMessageDialog(null, "Kaydınızı Basarıyla Guncellediniz !");
        listeguncelle();

        temizle();


    }//GEN-LAST:event_guncelle_butonActionPerformed

    private void temizle_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_temizle_butonActionPerformed
        // TODO add your handling code here:
        temizle();


    }//GEN-LAST:event_temizle_butonActionPerformed

    private void txt_faturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_faturaActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_faturaActionPerformed

    private void sil_butonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_butonActionPerformed
        // TODO add your handling code here:
        modelim.setRowCount(0);
        int no = Integer.parseInt(txt_belgeno.getText());
        String sqlsorgu = "delete from garantibelge_tbl where garantibelge_kayitno=" + no;
        veritabanibaglanti baglanti = new veritabanibaglanti();
        baglanti.sqlislemler(sqlsorgu);
        JOptionPane.showMessageDialog(null, "Kaydınızı Basarıyla Sildiniz !");
        listeguncelle();//sildikten sonra tabloyu güncellemek için

        temizle();//icini temizlesin diye


    }//GEN-LAST:event_sil_butonActionPerformed

    private void txt_faturaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_faturaMouseClicked
        // TODO add your handling code here:
        JFileChooser fileChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("JPG & GIF Images", "png", "gif");//Fitreliyoruz
        fileChooser.setFileFilter(filter);
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));//Gecerli projenin dosya yolu
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            txt_fatura.setText(selectedFile.getAbsolutePath());
        }
    }//GEN-LAST:event_txt_faturaMouseClicked

    private void buton_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buton_gosterActionPerformed
        // TODO add your handling code here:

        File file = new File("");

        //first check if Desktop is supported by Platform or not
        if (!Desktop.isDesktopSupported()) {
            System.out.println("Desktop is not supported");
            return;
        }

        Desktop desktop = Desktop.getDesktop();
        if (file.exists()) {
            try {
                desktop.open(file);
            } catch (IOException ex) {
                Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        //let's try to open PDF file
        file = new File(txt_fatura.getText());
        if (file.exists()) {
            try {
                desktop.open(file);
            } catch (IOException ex) {
                Logger.getLogger(FaturaDuzenlemeFormu.class.getName()).log(Level.SEVERE, null, ex);
            }

        }

    }//GEN-LAST:event_buton_gosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GarantiBelgesiDuzenlemeFormu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GarantiBelgesiDuzenlemeFormu().setVisible(true);
            }
        });
    }

    public void listeguncelle() {
        modelim.setRowCount(0);//mevcut tablonun icini sifirliyoruz herseferinde digerinin ustune eklenmesin diye
        veritabanibaglanti baglanti = new veritabanibaglanti();
        try {
            ResultSet res1 = baglanti.garantisisuresiazalanurunler();
            modelim.setColumnIdentifiers(sutun);
            while (res1.next()) {
                satirlar[0] = res1.getString("garantibelge_kayitno");
                satirlar[1] = res1.getString("garantibelge_urununturu");
                satirlar[2] = res1.getString("garantibelge_urununmarkasi");
                satirlar[3] = res1.getString("garantibelge_urununmodeli");
                satirlar[4] = res1.getString("garantibelge_urununadi");
                satirlar[5] = res1.getString("garantibelge_urununserino");
                satirlar[6] = res1.getString("garantibelge_urunungarantibitissuresi");
                satirlar[7] = res1.getString("garantibelge_urununfaturasi");

                modelim.addRow(satirlar);//yukarida tamımladigimiz satirlari rowsa ekledik 
            }

        } catch (Exception e) {
            // TODO: handle exception
        }

    }

    public void temizle() {
        txt_belgeno.setText("");
        txt_fatura.setText("");
        txt_marka.setText("");
        txt_model.setText("");
        txt_serino.setText("");
        txt_urunadi.setText("");
        cmbx_urunturu.setSelectedIndex(0);
        txt_belgeno.setEnabled(true);
        sil_buton.setEnabled(false);
        guncelle_buton.setEnabled(false);

        sil_buton.setEnabled(false);

        guncelle_buton.setEnabled(false);
        buton_goster.setEnabled(false);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buton_goster;
    private javax.swing.JComboBox<String> cmbx_urunturu;
    private com.toedter.calendar.JDateChooser dc_garantibitistarihi;
    private javax.swing.JButton guncelle_buton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton listele_buton;
    private javax.swing.JButton sil_buton;
    private javax.swing.JButton temizle_buton;
    private javax.swing.JTextField txt_belgeno;
    private javax.swing.JTextField txt_fatura;
    private javax.swing.JTextField txt_marka;
    private javax.swing.JTextField txt_model;
    private javax.swing.JTextField txt_serino;
    private javax.swing.JTextField txt_urunadi;
    // End of variables declaration//GEN-END:variables
void formuniconunuayarla() {
        Image Evim = new ImageIcon(GarantiBelgesiDuzenlemeFormu.class.getResource("Evim.jpg")).getImage();//resmi cektik burada classin ismi yazilacak burada ilk ilgili class icin 
        setIconImage(Evim);
    }

}
